[package]
name = "hops-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["tokio"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0"
